@port = {{$dotenv PORT}}
@domain = {{$dotenv HOST}}
@protocol = http
@apiPrefix = /api
@baseUrl = {{protocol}}://{{domain}}:{{port}}{{apiPrefix}}
@specificApiPrefix = /api/v1
@specificBaseUrl = {{protocol}}://{{domain}}:{{port}}{{specificApiPrefix}}
@versionUrl = {{baseUrl}}/version
@specificVersionUrl = {{specificBaseUrl}}/version

@authUrl = {{baseUrl}}/token
@usersUrl = {{baseUrl}}/users

GET {{versionUrl}}
####
GET {{specificVersionUrl}}

####
http://127.0.0.1:3333/
