@port = {{$dotenv PORT}}
@domain = {{$dotenv HOST}}
@protocol = http
@apiPrefix = /api
@baseUrl = {{protocol}}://{{domain}}:{{port}}{{apiPrefix}}
@specificApiPrefix = /api/v1
@specificBaseUrl = {{protocol}}://{{domain}}:{{port}}{{specificApiPrefix}}

@authUrl = {{baseUrl}}/login
@postsUrl = {{baseUrl}}/posts

# @name login
POST {{authUrl}}
Content-Type: application/x-www-form-urlencoded

email=Odie_Kshlerin3@example.org
&password=secret

####
POST {{postsUrl}}
Content-Type:application/json
Authorization: Bearer {{login.response.body.token}}
Accept: application/json

{
  "title":12,
  "description":"fd"
}
